config/routes.rb
Rails.application.routes.draw do
  resources :stock_prices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock_price.rb
# == Schema Information
#
# Table name: stock_prices
#
#  id         :integer          not null, primary key
#  symbol     :string
#  date       :date
#  open       :decimal(, )
#  high       :decimal(, )
#  low        :decimal(, )
#  close      :decimal(, )
#  volume     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class StockPrice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stock_prices_controller.rb
class StockPricesController < ApplicationController
  before_action :set_stock_price, only: [:show, :edit, :update, :destroy]

  # GET /stock_prices
  # GET /stock_prices.json
  def index
    @stock_prices = StockPrice.all

    # @maximum_high = 0.0
    # @stock_prices.each do |stock_price|
    #   @maximum_high = stock_price.high if stock_price.high > @maximum_high
    # end

    @week_count = StockPrice.count

    @maximum_high = StockPrice.maximum(:high)
    @minimum_low = StockPrice.minimum(:low)
    @average_close = StockPrice.average(:close)

    @maximum_volume = StockPrice.maximum(:volume)
    @minimum_volume = StockPrice.minimum(:volume)
    @total_volume = StockPrice.sum(:volume)

    @week_of_maximum_high = StockPrice.order(high: :desc).limit(1).first
  end

  # GET /stock_prices/1
  # GET /stock_prices/1.json
  def show
  end

  # GET /stock_prices/new
  def new
    @stock_price = StockPrice.new
  end

  # GET /stock_prices/1/edit
  def edit
  end

  # POST /stock_prices
  # POST /stock_prices.json
  def create
    @stock_price = StockPrice.new(stock_price_params)

    respond_to do |format|
      if @stock_price.save
        format.html { redirect_to @stock_price, notice: 'Stock price was successfully created.' }
        format.json { render :show, status: :created, location: @stock_price }
      else
        format.html { render :new }
        format.json { render json: @stock_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_prices/1
  # PATCH/PUT /stock_prices/1.json
  def update
    respond_to do |format|
      if @stock_price.update(stock_price_params)
        format.html { redirect_to @stock_price, notice: 'Stock price was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_price }
      else
        format.html { render :edit }
        format.json { render json: @stock_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_prices/1
  # DELETE /stock_prices/1.json
  def destroy
    @stock_price.destroy
    respond_to do |format|
      format.html { redirect_to stock_prices_url, notice: 'Stock price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_price
      @stock_price = StockPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_price_params
      params.require(:stock_price).permit(:symbol, :date, :open, :high, :low, :close, :volume)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_prices_helper.rb
module StockPricesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockstandard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stock_prices/_form.html.erb
<%= form_with(model: stock_price, local: true) do |form| %>
  <% if stock_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock_price.errors.count, "error") %> prohibited this stock_price from being saved:</h2>

      <ul>
      <% stock_price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :stock_price_symbol %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :stock_price_date %>
  </div>

  <div class="field">
    <%= form.label :open %>
    <%= form.text_field :open, id: :stock_price_open %>
  </div>

  <div class="field">
    <%= form.label :high %>
    <%= form.text_field :high, id: :stock_price_high %>
  </div>

  <div class="field">
    <%= form.label :low %>
    <%= form.text_field :low, id: :stock_price_low %>
  </div>

  <div class="field">
    <%= form.label :close %>
    <%= form.text_field :close, id: :stock_price_close %>
  </div>

  <div class="field">
    <%= form.label :volume %>
    <%= form.number_field :volume, id: :stock_price_volume %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stock_prices/edit.html.erb
<h1>Editing Stock Price</h1>

<%= render 'form', stock_price: @stock_price %>

<%= link_to 'Show', @stock_price %> |
<%= link_to 'Back', stock_prices_path %>

app/views/stock_prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stock Prices</h1>

<dl>
  <dt>Period</dt>
  <dd><%= pluralize @week_count, 'week' %></dd>

  <dt>Maximum High</dt>
  <dd><%= number_to_currency @maximum_high %></dd>

  <dt>Minimum Low</dt>
  <dd><%= number_to_currency @minimum_low %></dd>

  <dt>Average Price</dt>
  <dd><%= number_to_currency @average_close %></dd>

  <dt>Maximum Volume</dt>
  <dd><%= number_to_human @maximum_volume %></dd>

  <dt>Minimum Volume</dt>
  <dd><%= number_to_human @minimum_volume %></dd>

  <dt>Total Volume</dt>
  <dd><%= number_to_human @total_volume %></dd>

  <dt>Week of Maximum High</dt>
  <dd><%= @week_of_maximum_high.date.to_formatted_s(:long) %></dd>
  <dd><%= @week_of_maximum_high.high %></dd>
</dl>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Date</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Volume</th>
    </tr>
  </thead>

  <tbody>
    <% @stock_prices.each do |stock_price| %>
      <tr>
        <td><%= stock_price.symbol %></td>
        <td><%= stock_price.date %></td>
        <td><%= number_to_currency stock_price.open %></td>
        <td><%= number_to_currency stock_price.high %></td>
        <td><%= number_to_currency stock_price.low %></td>
        <td><%= number_to_currency stock_price.close %></td>
        <td><%= number_to_human stock_price.volume %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock Price', new_stock_price_path %>

app/views/stock_prices/new.html.erb
<h1>New Stock Price</h1>

<%= render 'form', stock_price: @stock_price %>

<%= link_to 'Back', stock_prices_path %>

app/views/stock_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @stock_price.symbol %>
</p>

<p>
  <strong>Date:</strong>
  <%= @stock_price.date %>
</p>

<p>
  <strong>Open:</strong>
  <%= @stock_price.open %>
</p>

<p>
  <strong>High:</strong>
  <%= @stock_price.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @stock_price.low %>
</p>

<p>
  <strong>Close:</strong>
  <%= @stock_price.close %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @stock_price.volume %>
</p>

<%= link_to 'Edit', edit_stock_price_path(@stock_price) %> |
<%= link_to 'Back', stock_prices_path %>